# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Cliente', max_length=50)),
                ('email', models.CharField(help_text='Email del Cliente', max_length=60)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha del Servicio')),
                ('url', models.URLField(blank=True, help_text='Url de pago del servicio', null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Tipo de Servicio', max_length=60)),
                ('url_default', models.URLField(help_text='Url Donde Se Paga el servicio')),
            ],
            options={
                'verbose_name': 'Tipo Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.AddField(
            model_name='servicios',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.TipoServicio'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario del Servicio', on_delete=django.db.models.deletion.CASCADE, to='services.Cliente'),
        ),
    ]
