# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para representar el tipo de servicio', null=True, upload_to='tiposervicios'),
        ),
    ]
