# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_tiposervicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha',
            field=models.DateTimeField(help_text='Fecha de Vencimiento Servicio'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para representar el tipo de servicio (Se recomienda el fondo transparente)', null=True, upload_to='tiposervicios'),
        ),
    ]
