# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170919_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha',
            field=models.DateField(help_text='Fecha de Vencimiento Servicio'),
        ),
    ]
