# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170929_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Nombre de la Plataforma', max_length=100)),
                ('platform_url', models.URLField(blank=True, help_text='Url del Plataforma', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_url',
        ),
        migrations.AlterField(
            model_name='services',
            name='services_type_service',
            field=models.ForeignKey(help_text='Tipo de servicio', on_delete=django.db.models.deletion.CASCADE, to='services.TypeService'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type_services_url_default',
            field=models.URLField(help_text='Url donde Se Paga el servicio'),
        ),
        migrations.AddField(
            model_name='services',
            name='services_platform',
            field=models.ForeignKey(default='', help_text='Plataforma del servicio', on_delete=django.db.models.deletion.CASCADE, to='services.Platform'),
            preserve_default=False,
        ),
    ]
