# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20171017_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Client', verbose_name='Cliente de la plataforma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(help_text='Email del Cliente', max_length=60, verbose_name='Email Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(help_text='Nombre del Cliente', max_length=50, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(help_text='Nombre de la Plataforma', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_url',
            field=models.URLField(blank=True, help_text='Url del Plataforma', null=True, verbose_name='Url plataforma'),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_date',
            field=models.DateField(help_text='Fecha de Vencimiento Servicio', verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_email_send',
            field=models.BooleanField(default=False, verbose_name='Email enviado'),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_platform',
            field=models.ForeignKey(help_text='Plataforma del servicio', on_delete=django.db.models.deletion.CASCADE, to='services.Platform', verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_type_service',
            field=models.ForeignKey(help_text='Tipo de servicio', on_delete=django.db.models.deletion.CASCADE, to='services.TypeService', verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='services',
            name='services_user',
            field=models.ForeignKey(help_text='Usuario del Servicio', on_delete=django.db.models.deletion.CASCADE, to='services.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type_Services_image',
            field=models.ImageField(blank=True, help_text='Imagen para representar el tipo de servicio (Se recomienda el fondo transparente)', null=True, upload_to='tiposervicios', verbose_name='Imagen tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type_services_name',
            field=models.CharField(help_text='Nombre del Tipo de Servicio', max_length=60, verbose_name='Nombre del tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type_services_url_default',
            field=models.URLField(help_text='Url donde Se Paga el servicio', verbose_name='Url del tipo de servicio'),
        ),
    ]
